name: build
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    name: "Build release binaries"
    needs: ["release-please"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pkgxdev/setup@v1
      - run: ./scripts/build.sh
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          path: ./dist/*

#      - name: Upload Release Artifact
#        if: ${{ steps.release.outputs.release_created }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: gh release upload  --clobber ${{ steps.release.outputs.tag_name }} ./dist/*
