name: ci
on:
  workflow_call:
  push:
    branches:
    - master
permissions:
  contents: write
  pull-requests: write
jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pkgxdev/setup@v1
        with:
          version: "1.1.6"
      - run: ./scripts/release.sh tests
