name: release-please
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  release_please:
    name: "Release Please"
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple

  build:
    name: "Build release binaries"
    needs: ["release_please"]
    if: ${{ needs.release_please.outputs.release_created == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: play-x86_64-unknown-linux-gnu.zip
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: play-aarch64-unknown-linux-gnu.zip
          - target: x86_64-apple-darwin
            os: macOS-14
            name: play-x86_64-apple-darwin.zip
          - target: aarch64-apple-darwin
            os: macOS-14-arm64
            name: play-aarch64-apple-darwin.zip
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pkgxdev/setup@v1
        with:
          version: "1.1.6"
      - run: ./scripts/build.sh ${{ matrix.target }}
      - name: Upload Release Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh release upload --clobber ${{ needs.release_please.outputs.tag_name }} ./dist/*
