name: release-please
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    name: "Release Please"
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple

  build:
    name: "Build release binaries"
    needs: ["release-please"]
    if: ${{ needs.release_please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pkgxdev/setup@v1
        with:
          version: "1.1.6"
      - run: ./scripts/build.sh
      - name: Upload Release Artifacts
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ needs.release_please.outputs.tag_name }} ./dist.*
